### ISSUE TITLE
Degrading

### ISSUE THREAD

**Issue by Fatihkazim** [MarkusMaal/BlueScreenSimulatorPlus#4]
Hi I downloaded 2.1 but It wanted me to update instead it downgraded to 2.0

**Comment by MarkusMaal** [comment]
This issue should now be fixed. In order to update now, you also need to make sure that the update server is **NOT** set to [http://markustegelane.000webhostapp.com/app](http://markustegelane.000webhostapp.com/app), because this server is offline now. Instead, set it to one of the following: [http://markustegelane.tk/app](http://markustegelane.tk/app), [http://markustegelane.ml/app](http://markustegelane.ml/app), or [https://markustegelane.online/app](https://markustegelane.online/app).
