### ISSUE TITLE
How to make a single-file .exe to prank?

### ISSUE THREAD

**Issue by wwwwjfjf** [MarkusMaal/BlueScreenSimulatorPlus#5]
It is avalibable in BSS.

**Comment by MarkusMaal** [comment]
This program will **never** officially support this feature due to concerns over creating scareware, which may be used to scam people by showing a fake blue screen and making them call a number, which would lead to a "technician", who would "fix" the computer for a high price.

This program offers a prank mode, which allows the simulator to run in the background and then display a blue screen after a period of time, when a specific process is started or when a USB device is inserted. It should be sufficient for friendly pranking purposes.
